### ISSUE TITLE
 报错 Error: listen EADDRNOTAVAIL: address not available 42.192.189.187:8082

### ISSUE THREAD

**Issue by Timorkong** [zhcxk1998/School-Partners#9]
? ?wds?:  Error: listen EADDRNOTAVAIL: address not available 42.192.189.187:8082
    at Server.setupListenHandle [as _listen2] (net.js:1300:21)
    at listenInCluster (net.js:1365:12)
    at doListen (net.js:1502:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: '42.192.189.187',
  port: 8082
}

**Comment by Timorkong** [comment]
IP是我在网上申请的

**Comment by zhcxk1998** [comment]
> EADDRNOTAVAIL

这个问题应该是IP地址有问题吧，检查一下应该就OK了，现在本地启动一下看看？
